development:
  adapter: postgresql
  encoding: unicode
  database: fabbit_development

test:
  adapter: postgresql
  encoding: unicode
  database: fabbit_test

production:
  adapter: postgresql
  encoding: unicode
  database: fabbit_production
